// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PLASTIC_WARFARE_PROJ.DbContextData;

#nullable disable

namespace PLASTIC_WARFARE_PROJ.Migrations.MainData
{
    [DbContext(typeof(MainDataContext))]
    [Migration("20240607152038_added_Index_UserId")]
    partial class added_Index_UserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.ModelOrder", b =>
                {
                    b.Property<int>("RenderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("RenderId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("ModelOrders");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int>("ModelsAmount")
                        .HasColumnType("int");

                    b.Property<int>("PlasticTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TotalWeight")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("PlasticTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.PlasticType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlasticTypes");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.Render_STL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rendered_STLs");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.ModelOrder", b =>
                {
                    b.HasOne("PLASTIC_WARFARE_PROJ.Models.Order", "Order")
                        .WithMany("ModelOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PLASTIC_WARFARE_PROJ.Models.Render_STL", "Render_STL")
                        .WithMany("ModelOrders")
                        .HasForeignKey("RenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Render_STL");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.Order", b =>
                {
                    b.HasOne("PLASTIC_WARFARE_PROJ.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PLASTIC_WARFARE_PROJ.Models.PlasticType", "PlasticType")
                        .WithMany("Orders")
                        .HasForeignKey("PlasticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("PlasticType");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.Order", b =>
                {
                    b.Navigation("ModelOrders");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.PlasticType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PLASTIC_WARFARE_PROJ.Models.Render_STL", b =>
                {
                    b.Navigation("ModelOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
